apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: words-api
spec:
  clusterIP: None
  ports:
    - port: 8080
      targetPort: 8080
      name: words-api
  selector:
    app: words-api
  