apiVersion: v1
kind: Service
metadata:
  name: sonarqube
  labels:
    app: sonarqube
spec:
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
      name: sonarqube
  selector:
    app: sonarqube